baseURL = 'https://nodecum.org/'
theme = 'PaperMod'
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = 'nodecum network'
    [languages.en.menu]
      [[languages.en.menu.main]]
         name = 'Home'
	 url = '/'
  [languages.de]
    title = 'nodecum Netzwerk'
    [languages.de.menu]
      [[languages.de.menu.main]]
         name = 'Start'
	 url = '/'
  [languages.fr]
    title = 'modecum ...'
