baseURL = 'https://nodecum.org/'
theme = 'zen'
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1
    title = 'nodecum network'
  [languages.de]
    languageName = 'Deutsch'
    contentDir = 'content/de' 
    weight = 2
    title = 'nodecum netz'
  [languages.fr]
    languageName = 'Français'
    contentDir = 'content/fr'
    title = 'modecum ...'
    weight = 3

[params]
  sidebar = false
  background_color_class = "bg-gray"
  realfavicongenerator = true
[markup]
  [goldmark]
    [renderer]
      unsafe = true # enable raw HTML in Markdown
# >o)