#+title: Vision
#+menu: main
#+weight: 2

L'être humain est au centre de notre image. Notre époque est riche en possibilités techniques. 
Mais celles-ci ne sont pas a priori une bénédiction. Les moyens de communication techniques sont 
impressionnants, mais ils ont des effets secondaires. Développer une éventuelle alternative est 
notre motivation.

- *Propriété / régime de propriété* \\
  Actuellement, l'utilisation des télécommunications, d'Internet et de la téléphonie mobile est 
  payée par l'utilisateur. Ce qui se passe avec les données pendant et après la communication 
  n'est pas vérifiable pour l'utilisateur et ne peut pas non plus être influencé.(censure, 
  établissement de profils de déplacement, etc.) \\
  Nous voyons la possibilité que seul l'achat des appareils de communication soit à la charge
  de l'utilisateur, mais que l'utilisation pour la communication n'exige aucun autre coût.
  Le réseau est la propriété des utilisateurs. La documentation et la programmation à 
  source libre créent la transparence et permettent d'évaluer le système.
- *Énergie - Autonomie* \\
  La communication numérique et le traitement des données actuels sont très gourmands en énergie. 
  Sans le réseau électrique, elle n'est pas possible.\\
  Notre système est autonome, pour autant qu'il y ait suffisamment de rayonnement solaire.
- *Structure* \\
  Les télécommunications et l'Internet ont une structure en étoile. 
  Pour envoyer un e-mail à un voisin, il se peut que les informations fassent le tour du monde.
  (en fonction de l'emplacement des serveurs de messagerie).\\
  Dans la structure maillée de notre réseau, on choisit un chemin direct.
  La défaillance des nœuds de communication peut être compensée par les nœuds voisins.
- *Exposition aux rayonnements* \\
  Le développement de la téléphonie mobile s'efforce d'obtenir un haut débit de données. 
  Cela est possible grâce à une fréquence plus élevée (2,4 GHz) ou à une orientation ciblée (5G).\\
  Notre réseau, en comparaison, a un débit de données, une fréquence et une densité d'énergie beaucoup plus faibles.
