#+title: Vision
#+menu: main
#+weight: 2

The human being should occupy the centre-stage. Our time is rich in
technical possibilities. But these are not a priori a blessing. The
technical means of communication are impressive, but have their side
effects. Our motivation is to develop a possible alternative.

- *Ownership / property* \\
  Currently, the use of telecommunication, internet and mobile telephony is
  paid for by the user. What happens to the data during the communication and
  afterwards is not verifiable for the user and also cannot be influenced (for
  example censorship, creation of movement profiles, etc.)\\
  We see the
  possibility of only purchasing the communication equipment and incurring
  one-time costs, after which the use for communication incurs no further
  costs. The network is the property of the users. The open source
  documentation and programming creates transparency and allows an evaluation
  of the system.
- *Energy - Autonomy* \\
  Today's digital communication and data processing requires a lot of energy.
  It is not possible without the power grid.\\
  Our system is self-sufficient, as
  long as there is enough solar radiation.
- *Structure* \\
  Telecommunication and the Internet have a star-shaped structure. To send an
  email to a neighbour it can be that the information is passed around the
  globe (depending on where the mail servers are located).\\
  In the mesh structure of our network, a direct path is chosen. The failure of
  communication nodes can be compensated by neighbouring nodes.
- *Radiation exposure* \\
  The development of mobile communication is aimed at achieving a high data
  throughput. This is achieved by a higher frequency (2.4 GHz) or a targeted
  alignment (5G).\\
  Compared to this, our network has a much lower data rate,
  lower frequency and energy density.
